# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
#filter = { only_tables = ["company","worker_types","department","group_types","contract","eq_group_list","equipment_type","project"]}
filter = { except_tables = ["eq_group","groups","pc_bind"]}